# Required: A short name for the action package
name: Excel

# Required: A description of what's in the action package.
description: USes local Excel files

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
  - python=3.10.14
  - uv=0.2.6
  pypi:
  - sema4ai-actions=0.9.2
  - pydantic=2.7.4
  - rpaframework=28.5.1
