# Required: A short name for the action package
name: Get random joke

# Required: A description of what's in the action package.
description: This simple example shows how to make API calls with Actions.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/tree/master/api-jokes/README.md

dependencies:
  conda-forge:
  - python=3.10.14
  - uv=0.2.6
  pypi:
  - sema4ai-actions=0.9.2
  - requests=2.31.0
