
# Required: A short name for the action package
name: Github

# Required: A description of what's in the action package.
description: Github api actions.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/Sema4AI/cookbook/tree/due-diligence/actions/github/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - uv=0.1.37
  pypi:
  - sema4ai-actions=0.3.1
  - requests=2.31.0

