
# Required: A short name for the action package
name: Claude Validator

# Required: A description of what's in the action package.
description: Uses Claude to Validate other LLMs answers.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
  - python=3.10.12
  - uv=0.1.37
  pypi:
  - sema4ai-actions=0.3.1
  - anthropic=0.21.3

