# Required: A short name for the action package
name: Donut OCR Action

# Required: A description of what's in the action package.
description: Action package description

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
  - python=3.10.14
  - uv=0.2.6
  - pytorch=2.1.2
  pypi:
  - sema4ai-actions=0.9.2
  - pydantic=2.7.4
  - transformers=4.39.3
  - pillow=10.3.0
  - sentencepiece=0.2.0
  - protobuf=5.26.1
