# Required: A short name for the action package
name: Dependency Due Diligenge Actions

# Required: A description of what's in the action package.
description: Extract data for due diligence checks for dependencies

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
  - python=3.10.12
  - uv=0.2.5
  pypi:
  - sema4ai-actions=0.9.1
  - requests=2.32.3
  - beautifulsoup4=4.12.3
  - anthropic=0.21.3

packaging:
  # This section is optional.
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
