
# Required: A short name for the action package
name: Google Search example
    
# Required: A description of what's in the action package.
description: The example shows how to open a browser (headless or not) and perform actions against a website.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/robocorp/actions-cookbook/tree/master/browser-google/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - uv=0.1.37
  pypi:
  - sema4ai-actions=0.3.1
  - robocorp-browser=2.3.3

