dependencies:
  conda-forge:
    - python=3.10.14
    - uv=0.2.6
  pypi:
    - sema4ai-actions=0.9.2
name: Secret Greeter

description: Greets user with a secret message

documentation: https://github.com/robocorp/robocorp/blob/master/action_server/docs/guides/07-secrets.md
