
# Required: A short name for the action package
name: Scraper

# Required: A description of what's in the action package.
description: Open a browser and extract site html from a website.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/Sema4AI/cookbook/tree/due-diligence/actions/scraper/README.md

dependencies:
  conda-forge:
  - python=3.10.12
  - uv=0.1.37
  pypi:
  - sema4ai-actions=0.3.1
  - robocorp-browser=2.3.3

