# Required: A short name for the action package
name: Agent Deployer

# Required: A description of what's in the action package.
description: Deploys agents to Sema4 Desktop based on yaml specification files.

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/...

dependencies:
  conda-forge:
    - python=3.10.14
    - uv=0.2.6
  pypi:
    - sema4ai-actions=0.9.1
    - requests=2.32.2
    - pyyaml=6.0.1

packaging:
  # By default, all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./venv/**
    - ./.venv/**
    - ./.DS_store/**
    - ./**/*.pyc
    - ./**/*.zip
